Repository trustbloc/adapter, pull requests merged in 2020-07, with the labels that each got.

#136 chore: Update aries framework go version
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/internal/mock/issuecredential/service.go
  test/bdd/fixtures/didcomm/.env
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#140 feat: [Issuer Adapter] Support for present proof protocol
  pkg/internal/mock/presentproof/client.go
  pkg/internal/mock/presentproof/service.go
  pkg/restapi/issuer/controller_test.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/rp/controller_test.go
  pkg/restapi/rp/operation/operations_test.go
  pkg/vc/issuer/credentials.go
  pkg/vc/issuer/credentials_test.go
  test/bdd/features/issuer_e2e.feature
  test/bdd/pkg/agent/agent_controller_steps.go
Labels: cla-signed

#141 refactor: #137 rp adapter: use explicit didcomm invitations
  pkg/internal/mock/connection/connection_lookup.go
  pkg/internal/mock/didexchange/client.go
  pkg/internal/mock/presentproof/client.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/rp/controller_test.go
  pkg/restapi/rp/operation/models.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/features/rp_e2e.feature
  test/bdd/go.mod
  test/bdd/pkg/rp/rp_steps.go
Labels: cla-signed

#144 test: #132 rp adapter: bdd test for didexchange with wallet
  pkg/restapi/rp/operation/operations.go
  test/bdd/features/rp_e2e.feature
  test/bdd/fixtures/adapter-rest/docker-compose.yml
  test/bdd/fixtures/didcomm/.env
  test/bdd/fixtures/didcomm/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/rp/rp_steps.go
Labels: cla-signed

#146 fix: #142 rp adapter: send consent VC to issuer adapter
  pkg/restapi/rp/operation/credentials.go
  pkg/restapi/rp/operation/credentials_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
Labels: cla-signed

#148 feat: [Issuer Adapter] Include manifest in CHAPI request to wallet
  cmd/issuer-adapter-vue/src/pages/WalletConnect.vue
  pkg/profile/issuer/profile.go
  pkg/profile/issuer/profile_test.go
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/vc/issuer/credentials.go
  pkg/vc/issuer/credentials_test.go
  pkg/vc/issuer/models.go
  test/bdd/features/issuer_e2e.feature
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/issuer/issuer_steps.go
Labels: cla-signed

#154 refactor: [Issuer Adapter] Update Consent Credential Model
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/vc/issuer/credentials.go
  pkg/vc/issuer/credentials_test.go
  pkg/vc/models.go
  test/bdd/pkg/agent/agent_controller_steps.go
Labels: cla-signed

#156 feat: [Issuer Adapter] Validate Consent Credential in Request presentation flow
  pkg/restapi/internal/common/http/common.go
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/vc/issuer/credentials.go
  pkg/vc/issuer/credentials_test.go
  test/bdd/pkg/agent/agent_controller_steps.go
Labels: cla-signed

#157 test: #147 rp adapter: bdd test - return data to the rp
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/internal/mock/didexchange/client.go
  pkg/internal/mock/presentproof/client.go
  pkg/restapi/rp/controller_test.go
  pkg/restapi/rp/operation/credentials.go
  pkg/restapi/rp/operation/credentials_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/features/rp_e2e.feature
  test/bdd/fixtures/didcomm/.env
  test/bdd/fixtures/didcomm/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/rp/jsonld.go
  test/bdd/pkg/rp/rp_steps.go
  test/bdd/pkg/rp/testdata/context/presentation_exchange.jsonld
  test/bdd/pkg/rp/testdata/context/schema.org.jsonld
  test/bdd/pkg/rp/testdata/context/trustbloc_example.jsonld
  test/bdd/pkg/rp/testdata/context/verifiable_credentials_v1.0.jsonld
Labels: cla-signed, rp adapter, test

#159 feat: [Issuer Adapter] Create Presentation with User Data
  Makefile
  images/mock/issuer/Dockerfile
  pkg/profile/issuer/profile.go
  pkg/profile/issuer/profile_test.go
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  test/bdd/bddtests_test.go
  test/bdd/cmd/issuer/main.go
  test/bdd/features/issuer_e2e.feature
  test/bdd/fixtures/integration/.env
  test/bdd/fixtures/integration/docker-compose.yml
  test/bdd/go.mod
  test/bdd/pkg/issuer/issuer_steps.go
Labels: cla-signed

#163 feat: [Issuer Adapter] Create connection record with RP from consent cred request
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  test/bdd/pkg/agent/agent_controller_steps.go
Labels: cla-signed

#160 refactor: #149 rp adapter: update jsonld contexts
  pkg/restapi/rp/operation/credentials.go
  pkg/restapi/rp/operation/credentials_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  pkg/restapi/rp/operation/testdata/context/consent-credential-v1.jsonld
  pkg/restapi/rp/operation/testdata/context/examples-ext-v1.jsonld
  pkg/restapi/rp/operation/testdata/context/trustbloc_example.jsonld
  pkg/vc/credentials.go
  pkg/vc/models.go
  test/bdd/pkg/rp/jsonld.go
  test/bdd/pkg/rp/testdata/context/consent-credential-v1.jsonld
  test/bdd/pkg/rp/testdata/context/examples-ext-v1.jsonld
  test/bdd/pkg/rp/testdata/context/trustbloc_example.jsonld
Labels: cla-signed, rp adapter

#166 feat: #165 rp adapter: redirect user back to rp renant
  cmd/rp-adapter-vue/src/pages/Credentials.vue
Labels: cla-signed, rp adapter

#172 feat: Support for VC/VP Signing
  cmd/adapter-rest/go.sum
  cmd/adapter-rest/startcmd/start.go
  cmd/adapter-rest/startcmd/start_test.go
  pkg/aries/api.go
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
  pkg/crypto/util.go
  pkg/did/trustbloc_did_creator.go
  pkg/internal/mock/diddoc/diddoc.go
  pkg/profile/issuer/profile.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/vc/api.go
  test/bdd/fixtures/adapter-rest/docker-compose.yml
  test/bdd/pkg/agent/agent_controller_steps.go
Labels: cla-signed

#174 chore: Update sidetree/did-method/vc-rest images
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/did/trustbloc_did_creator.go
  test/bdd/fixtures/did-trustbloc/.env
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#176 feat: [Issuer Adapter] Add Issuer name to the Manifest VC
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/vc/issuer/credentials.go
  pkg/vc/issuer/credentials_test.go
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#177 fix: rp-adapter-vue: unhandled promise when fetching CHAPI request from backend
  cmd/rp-adapter-vue/src/pages/Credentials.vue
Labels: bug, cla-signed, rp adapter

#179 fix: #171 rp-adapter: query types in CHAPI request
  cmd/rp-adapter-vue/src/pages/Credentials.vue
Labels: bug, cla-signed, rp adapter

#181 feat: [Issuer Adapter] Sign Consent Credential
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/did/trustbloc_did_creator.go
  pkg/profile/issuer/profile.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/rp/operation/testdata/context/consent-credential-v1.jsonld
  pkg/vc/issuer/credentials.go
  pkg/vc/models.go
  test/bdd/fixtures/didcomm/.env
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/context/context.go
  test/bdd/pkg/rp/testdata/context/consent-credential-v1.jsonld
Labels: cla-signed

#183 refactor: #169 rp-adapter: use public DIDs in didcomm invitations
  cmd/adapter-rest/startcmd/start.go
  pkg/did/trustbloc_did_creator.go
  pkg/did/trustbloc_did_creator_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/fixtures/adapter-rest/docker-compose.yml
Labels: cla-signed, refactor, rp adapter

#185 feat: #182 configure logging level
  cmd/adapter-rest/startcmd/start.go
Labels: cla-signed, enhancement, rp adapter

#186 chore: [Issuer Adapter] Add log statements
  pkg/restapi/internal/common/http/common.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
Labels: cla-signed

#189 fix: #187 rp-adapter: various fixes
  cmd/adapter-rest/startcmd/start.go
  cmd/adapter-rest/startcmd/start_test.go
  cmd/rp-adapter-vue/src/pages/Credentials.vue
  pkg/restapi/rp/operation/credentials.go
  pkg/restapi/rp/operation/credentials_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/features/healthcheck_api.feature
  test/bdd/fixtures/adapter-rest/docker-compose.yml
  test/bdd/pkg/rp/rp_steps.go
Labels: bug, cla-signed, rp adapter

#193 refactor: [Issuer Adapter] Expect VP instead of VC in presentation request
  cmd/adapter-rest/startcmd/start.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  test/bdd/pkg/agent/agent_controller_steps.go
Labels: cla-signed

#196 feat: [Issuer Adapter] TLS Support
  cmd/adapter-rest/startcmd/start.go
  test/bdd/features/healthcheck_api.feature
  test/bdd/pkg/bddutil/util.go
  test/bdd/pkg/issuer/issuer_steps.go
Labels: cla-signed

#198 fix: #197 rp-adapter: error while parsing VC from issuer
  pkg/restapi/rp/operation/operations.go
Labels: bug, cla-signed, rp adapter

#204 feat: [Issuer Adapter] UI Update
  cmd/issuer-adapter-vue/package-lock.json
  cmd/issuer-adapter-vue/package.json
  cmd/issuer-adapter-vue/postcss.config.js
  cmd/issuer-adapter-vue/src/App.vue
  cmd/issuer-adapter-vue/src/assets/css/tailwind.css
  cmd/issuer-adapter-vue/src/main.js
  cmd/issuer-adapter-vue/src/pages/WalletConnect.vue
  cmd/issuer-adapter-vue/src/pages/layout/Footer.vue
  cmd/issuer-adapter-vue/src/pages/layout/Layout.vue
  cmd/issuer-adapter-vue/src/router/index.js
  cmd/issuer-adapter-vue/tailwind.config.js
Labels: cla-signed

#206 fix: Update page titles
  cmd/issuer-adapter-vue/public/index.html
  cmd/rp-adapter-vue/public/index.html
Labels: cla-signed

#205 fix: #200 rp adapter UI
  cmd/issuer-adapter-vue/package-lock.json
  cmd/rp-adapter-vue/package-lock.json
  cmd/rp-adapter-vue/package.json
  cmd/rp-adapter-vue/postcss.config.js
  cmd/rp-adapter-vue/src/App.vue
  cmd/rp-adapter-vue/src/assets/css/tailwind.css
  cmd/rp-adapter-vue/src/main.js
  cmd/rp-adapter-vue/src/pages/Credentials.vue
  cmd/rp-adapter-vue/src/pages/layout/Footer.vue
  cmd/rp-adapter-vue/src/pages/layout/Layout.vue
  cmd/rp-adapter-vue/src/router/index.js
  cmd/rp-adapter-vue/tailwind.config.js
Labels: bug, cla-signed, rp adapter

#207 fix: linting error
  cmd/rp-adapter-vue/postcss.config.js
  cmd/rp-adapter-vue/src/assets/css/tailwind.css
  cmd/rp-adapter-vue/tailwind.config.js
Labels: bug, cla-signed

#208 fix: [Issuer Adapter] Remove user button clicks during Wallet Connect
  cmd/issuer-adapter-vue/src/pages/WalletConnect.vue
Labels: cla-signed

#210 refactor: Update adapter code based on latest aries-framework-go changes
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/aries/api.go
  pkg/restapi/issuer/controller_test.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/rp/controller_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/fixtures/didcomm/.env
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#214 docs: Issuer Adapter API/Integration doc
  README.md
  docs/issuer/README.md
  pkg/restapi/issuer/operation/operations.go
Labels: cla-signed

#217 fix: #216 use edge-core mysql storage
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  cmd/adapter-rest/startcmd/start.go
  cmd/adapter-rest/startcmd/start_test.go
  go.mod
  go.sum
  pkg/db/rp/rp.go
  test/bdd/fixtures/adapter-rest/docker-compose.yml
  test/bdd/fixtures/adapter-rest/mysql-config/mysql_config.sql
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#218 feat: update to new presentation exchange
  pkg/presentationex/api.go
  pkg/presentationex/provider.go
  pkg/presentationex/provider_test.go
Labels: cla-signed

#215 docs: rp adapter docs
  README.md
  docs/issuer/README.md
  docs/rp/README.md
  docs/rp/rp_adapter_architecture.svg
  docs/rp/rp_adapter_overview.svg
Labels: cla-signed, documentation, rp adapter

#221 fix: Exclude licence check in svg files
  scripts/check_license.sh
Labels: cla-signed

#220 refactor: Rename ConsentCredential to AuthorizationCredential
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/rp/operation/credentials.go
  pkg/restapi/rp/operation/credentials_test.go
  pkg/restapi/rp/operation/operations_test.go
  pkg/restapi/rp/operation/testdata/context/authorization-credential-v1.jsonld
  pkg/vc/issuer/credentials.go
  pkg/vc/issuer/credentials_test.go
  pkg/vc/models.go
  test/bdd/features/rp_e2e.feature
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/rp/jsonld.go
  test/bdd/pkg/rp/rp_steps.go
  test/bdd/pkg/rp/testdata/context/authorization-credential-v1.jsonld
Labels: cla-signed
