Repository trustbloc/adapter, pull requests merged in 2020-08, with the labels that each got.

#224 fix: slow image build times
  Makefile
  images/adapter-rest-base/Dockerfile
  images/issuer-adapter-rest/Dockerfile
  images/rp-adapter-rest/Dockerfile
Labels: bug, cla-signed

#223 refactor: rpadapter: #29 use transient storage
  cmd/adapter-rest/startcmd/start.go
  pkg/restapi/rp/controller_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  pkg/restapi/rp/operation/transient_data.go
Labels: cla-signed, refactor, rp adapter

#228 refactor: #225 use oob invitations instead of didexchange
  cmd/adapter-rest/startcmd/start.go
  pkg/internal/mock/outofband/client.go
  pkg/internal/mock/outofband/service.go
  pkg/restapi/issuer/controller_test.go
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/rp/operation/models.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/features/issuer_e2e.feature
  test/bdd/features/rp_e2e.feature
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/issuer/issuer_steps.go
  test/bdd/pkg/rp/rp_steps.go
Labels: cla-signed, refactor, rp adapter

#229 chore: go mod tidy
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.sum
  test/bdd/go.mod
  test/bdd/go.sum
Labels: chore, cla-signed

#235 fix: [RP Adapter] Support to configure scopes
  pkg/db/rp/models.go
  pkg/restapi/rp/operation/models.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/features/rp_e2e.feature
  test/bdd/pkg/rp/rp_steps.go
Labels: cla-signed

#237 feat: #236 configure database connection retries
  cmd/adapter-rest/startcmd/start.go
  cmd/adapter-rest/startcmd/start_test.go
  test/bdd/fixtures/adapter-rest/docker-compose.yml
Labels: cla-signed, enhancement

#243 feat: Configure governance vcs url in adapter cmd
  cmd/adapter-rest/startcmd/start.go
Labels: cla-signed

#242 chore: copy aries framework presentation-exchange API
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/presexch/api.go
  pkg/presexch/api_test.go
  scripts/check_license.sh
  test/bdd/go.sum
Labels: chore, cla-signed

#245 refactor: [Issuer Adapter] Sign VC created from User data from the Issuer
  .golangci.yml
  docs/issuer/README.md
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/vc/api.go
  pkg/vc/issuer/credentials.go
  test/bdd/cmd/issuer/main.go
Labels: cla-signed

#246 feat: #234 rp-adapter: support configuration of presentation-exchange scope
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  cmd/adapter-rest/startcmd/start.go
  cmd/adapter-rest/startcmd/start_test.go
  go.sum
  pkg/db/rp/models.go
  pkg/presentationex/api.go
  pkg/presentationex/provider.go
  pkg/presentationex/provider_test.go
  pkg/restapi/rp/operation/credentials.go
  pkg/restapi/rp/operation/models.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  pkg/vc/rp/models.go
  test/bdd/fixtures/testdata/presentationdefinitions.json
  test/bdd/go.sum
Labels: cla-signed, enhancement, rp adapter

#249 chore: Update edge-core dependency
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/profile/issuer/profile.go
  pkg/profile/issuer/profile_test.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#251 feat: Create governance vc through governance VCS
  cmd/adapter-rest/startcmd/start.go
  cmd/adapter-rest/startcmd/start_test.go
  pkg/governance/provider.go
  pkg/governance/provider_test.go
  pkg/internal/mock/governance/provider.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/fixtures/adapter-rest/docker-compose.yml
  test/bdd/fixtures/integration/.env
  test/bdd/fixtures/integration/docker-compose.yml
  test/bdd/fixtures/integration/governance-vcs-profiles.sh
Labels: cla-signed

#252 feat: #247 rp-adapter: evaluate wallet's response against the definitions
  pkg/internal/common/adapterutil/adapterutil.go
  pkg/presexch/api.go
  pkg/presexch/api_test.go
  pkg/restapi/rp/operation/credentials.go
  pkg/restapi/rp/operation/credentials_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  pkg/restapi/rp/operation/testdata/context/credit-score-v1.jsonld
  pkg/restapi/rp/operation/testdata/context/mdl-v1.jsonld
  pkg/vc/api.go
  pkg/vc/models.go
  pkg/vc/rp/models.go
  test/bdd/features/rp_e2e.feature
  test/bdd/fixtures/testdata/presentationdefinitions.json
  test/bdd/pkg/rp/jsonld.go
  test/bdd/pkg/rp/rp_steps.go
  test/bdd/pkg/rp/testdata/context/mdl-v1.jsonld
Labels: cla-signed, enhancement, rp adapter

#257 fix: #256 presentation exchange schema URI should be an array
  cmd/adapter-rest/startcmd/start_test.go
  pkg/internal/common/adapterutil/adapterutil.go
  pkg/presentationex/provider_test.go
  pkg/presexch/api.go
  pkg/presexch/api_test.go
  pkg/restapi/rp/operation/credentials_test.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/fixtures/testdata/presentationdefinitions.json
  test/bdd/pkg/rp/rp_steps.go
Labels: bug, cla-signed, rp adapter

#259 feat: Configure token request parameter
  cmd/adapter-rest/startcmd/start.go
  cmd/adapter-rest/startcmd/start_test.go
Labels: cla-signed

#261 feat: Retrieve governance vc
  go.sum
  pkg/internal/mock/governance/provider.go
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/rp/operation/models.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/rp/rp_steps.go
Labels: cla-signed

#263 test: [Issuer Adapter] Update BDD tests to show support for multiple issuers
  test/bdd/cmd/issuer/main.go
  test/bdd/features/issuer_e2e.feature
  test/bdd/pkg/agent/agent_controller_steps.go
Labels: cla-signed

#266 fix: Assign governance provider to a interface rather than struct
  cmd/adapter-rest/startcmd/start.go
Labels: cla-signed

#276 fix: Issuer adapter chapi window loading fix and minor UI fix
  cmd/issuer-adapter-vue/src/pages/WalletConnect.vue
  cmd/issuer-adapter-vue/src/pages/components/Footer.vue
  cmd/issuer-adapter-vue/src/pages/views/Landing.vue
  cmd/issuer-adapter-vue/tailwind.config.js
  cmd/rp-adapter-vue/src/pages/Credentials.vue
  cmd/rp-adapter-vue/src/pages/components/Footer.vue
  cmd/rp-adapter-vue/tailwind.config.js
Labels: cla-signed

#264 chore: update bdd test to latest trustbloc-did-method
  Makefile
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  scripts/build-did-method-cli.sh
  scripts/generate_test_config.sh
  test/bdd/bddtests_test.go
  test/bdd/fixtures/did-trustbloc/config-data/config.json
  test/bdd/fixtures/did-trustbloc/config-data/stakeholder-one.trustbloc.local:8088.json
  test/bdd/fixtures/did-trustbloc/config-data/stakeholderone_jwk.json
  test/bdd/fixtures/did-trustbloc/config-data/testnet.trustbloc.local.json
  test/bdd/fixtures/did-trustbloc/discovery-compose.yml
  test/bdd/fixtures/did-trustbloc/docker-compose.yml
  test/bdd/generate_config.sh
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#282 feat: Support for Credential with Assurance Credential flow
  pkg/profile/issuer/profile.go
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/vc/api.go
  test/bdd/cmd/issuer/go.mod
  test/bdd/cmd/issuer/go.sum
  test/bdd/cmd/issuer/main.go
  test/bdd/features/issuer_e2e.feature
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/issuer/issuer_steps.go
Labels: cla-signed

#286 fix: change issue governance vc order
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/rp/operation/operations.go
Labels: cla-signed

#284 refactor: #277 rp-adapter id_token response
  pkg/presentationex/provider.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/pkg/rp/rp_steps.go
Labels: cla-signed, refactor, rp adapter

#287 refactor: [Issuer Adapter] Remove 'manifest' attribute in chapi request
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
Labels: cla-signed

#288 chore: [Issuer Adapter] Add credential name and description
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  test/bdd/cmd/issuer/main.go
Labels: cla-signed

#290 refactor: use credentials in DIDconnect request to send gov vc
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/rp/operation/models.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/rp/rp_steps.go
Labels: cla-signed

#292 fix: RP - sending credentials in didconnect CHAPI request
  cmd/rp-adapter-vue/src/pages/Credentials.vue
Labels: cla-signed

#291 fix: #254 rp-adapter bugs
  cmd/rp-adapter-vue/src/pages/Credentials.vue
  docs/rp/README.md
  pkg/restapi/rp/controller_test.go
  pkg/restapi/rp/operation/credentials_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/pkg/rp/rp_steps.go
Labels: bug, cla-signed, rp adapter

#294 chore: update vcs image
  test/bdd/fixtures/integration/.env
Labels: cla-signed

#296 docs: rp-adapter docs
  docs/rp/README.md
  docs/rp/architecture.md
  docs/rp/integration/relying_parties.md
  docs/rp/protocols.md
Labels: cla-signed, documentation, rp adapter

#299 chore: update sidetree-mock to 0.1.4
  test/bdd/fixtures/did-trustbloc/.env
Labels: cla-signed

#307 docs: Update issuer adapter docs
  docs/issuer/README.md
  docs/issuer/images/issuer_adapter_sequence_diagram.svg
  docs/issuer/issuer_integration.md
  docs/issuer/rp_adapter_integration.md
  docs/issuer/wallet_integration.md
Labels: cla-signed

#308 fix: rp-adapter validation of VP proofs
  ci/azure-pipelines.yml
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  cmd/adapter-rest/startcmd/start.go
  go.mod
  go.sum
  pkg/aries/api.go
  pkg/crypto/crypto.go
  pkg/crypto/util.go
  pkg/crypto/util_test.go
  pkg/did/trustbloc_did_creator.go
  pkg/did/trustbloc_did_creator_test.go
  pkg/presexch/api.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/rp/controller_test.go
  pkg/restapi/rp/operation/credentials.go
  pkg/restapi/rp/operation/credentials_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  pkg/restapi/rp/operation/support_test.go
  pkg/vc/issuer/credentials.go
  test/bdd/features/rp_e2e.feature
  test/bdd/fixtures/didcomm/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/context/context.go
  test/bdd/pkg/rp/jsonld.go
  test/bdd/pkg/rp/rp_steps.go
Labels: bug, cla-signed, issuer-adapter, rp adapter

#311 fix: Update adapter azure pipeline link
  README.md
Labels: cla-signed

#310 chore: release 0.1.4
  ci/version_var.sh
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/fixtures/did-trustbloc/.env
  test/bdd/fixtures/didcomm/.env
  test/bdd/fixtures/integration/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/rp/rp_steps.go
Labels: chore, cla-signed
