Repository trustbloc/adapter, pull requests merged in 2020-10, with the labels that each got.

#338 chore: Update aries-framework-go
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/crypto/util_test.go
  pkg/internal/mock/outofband/service.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/rp/operation/support_test.go
  test/bdd/fixtures/didcomm/.env
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#345 feat: Support for Message Handling Service
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/internal/mock/messenger/messenger.go
  pkg/message/models.go
  pkg/message/msg_svc.go
  pkg/message/msg_svc_test.go
  pkg/message/service.go
  pkg/message/service_test.go
  pkg/message/support_test.go
  test/bdd/fixtures/didcomm/.env
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#346 chore: update trustbloc-did-method revision
  cmd/adapter-rest/go.sum
  cmd/adapter-rest/startcmd/start.go
  go.mod
  go.sum
  pkg/governance/provider.go
  pkg/governance/provider_test.go
  test/bdd/fixtures/did-trustbloc/.env
  test/bdd/fixtures/did-trustbloc/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/context/context.go
  test/bdd/pkg/rp/rp_steps.go
Labels: cla-signed

#348 test: Fetch PeerDIDDoc bdd tests
  Makefile
  test/bdd/features/issuer_e2e.feature
  test/bdd/fixtures/didcomm/.env
  test/bdd/fixtures/didcomm/docker-compose.yml
  test/bdd/fixtures/integration/docker-compose.yml
  test/bdd/pkg/agent/agent_controller_steps.go
  test/mock/cmd/issuer/go.mod
  test/mock/cmd/issuer/go.sum
  test/mock/cmd/issuer/main.go
  test/mock/cmd/webhook/go.mod
  test/mock/cmd/webhook/go.sum
  test/mock/cmd/webhook/main.go
  test/mock/images/issuer/Dockerfile
  test/mock/images/webhook/Dockerfile
Labels: cla-signed

#349 refactor: BDD tests - consistent mock component names and move msg svc to separate file
  test/bdd/bddtests_test.go
  test/bdd/features/issuer_e2e.feature
  test/bdd/fixtures/didcomm/.env
  test/bdd/fixtures/didcomm/docker-compose.yml
  test/bdd/fixtures/integration/.env
  test/bdd/fixtures/integration/docker-compose.yml
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/agent/msg_svc.go
  test/bdd/pkg/bddutil/util.go
Labels: cla-signed

#350 feat: Routing - Handle Create Connection Req
  pkg/message/models.go
  pkg/message/service.go
  pkg/message/service_test.go
  pkg/message/support_test.go
  pkg/restapi/issuer/operation/operations.go
Labels: cla-signed

#351 chore: Add dockerignore to skip npm_modules in build context
  .dockerignore
Labels: cla-signed

#352 refactor: Consolidate healthcheck into respective modes (issuer and rp)
  ci/azure-pipelines.yml
  scripts/check_integration.sh
  test/bdd/features/healthcheck_api.feature
  test/bdd/features/issuer_e2e.feature
  test/bdd/features/rp_e2e.feature
Labels: cla-signed

#353 fix: codecov
  .gitignore
  scripts/check_unit.sh
Labels: cla-signed

#355 chore: Update aries-framework-go
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  cmd/adapter-rest/startcmd/start.go
  go.mod
  go.sum
  pkg/aries/api.go
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
  pkg/crypto/util_test.go
  pkg/message/service.go
  pkg/message/service_test.go
  pkg/message/support_test.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/issuer/operation/support_test.go
  pkg/restapi/rp/operation/credentials.go
  pkg/restapi/rp/operation/credentials_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  pkg/restapi/rp/operation/support_test.go
  test/bdd/fixtures/did-trustbloc/.env
  test/bdd/fixtures/integration/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/bddutil/util.go
  test/bdd/pkg/context/context.go
Labels: cla-signed

#357 refactor: Aries Framework Update - Use mysql from ext repo
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  cmd/adapter-rest/startcmd/start.go
  cmd/adapter-rest/startcmd/start_test.go
  go.mod
  go.sum
  pkg/internal/mock/messenger/messenger.go
  test/bdd/fixtures/integration/.env
  test/bdd/fixtures/integration/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#358 feat: Blinded Routing - Router registration
  pkg/internal/mock/mediator/client.go
  pkg/message/service.go
  pkg/message/service_test.go
  pkg/message/support_test.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  test/bdd/features/issuer_e2e.feature
  test/bdd/fixtures/integration/.env
  test/bdd/fixtures/integration/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/agent/msg_svc.go
Labels: cla-signed

#359 test: Update hub-router dependency
  test/bdd/fixtures/integration/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/agent/msg_svc.go
Labels: cla-signed

#360 feat: Blinded Routing - Support to use router's endpoint in AuthZCred
  pkg/internal/mock/mediator/client.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/issuer/operation/support_test.go
  pkg/route/models.go
  pkg/route/msg_svc.go
  pkg/route/msg_svc_test.go
  pkg/route/service.go
  pkg/route/service_test.go
  pkg/route/support_test.go
  test/bdd/pkg/agent/msg_svc.go
Labels: cla-signed

#362 test: Blinded Routing - AuthZ bdd tests
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/issuer/operation/support_test.go
  pkg/route/service.go
  pkg/route/service_test.go
  pkg/route/support_test.go
  test/bdd/features/issuer_e2e.feature
  test/bdd/pkg/agent/agent_controller_steps.go
Labels: cla-signed

#366 docs: #363 rpadapter/wallet integration
  docs/rp/README.md
  docs/rp/integration/wallet_rpadapter_int_overview.puml
  docs/rp/integration/wallets.md
Labels: cla-signed, documentation, rp adapter

#368 fix: rpadapter-wallet integration docs image url
  docs/rp/integration/wallets.md
Labels: cla-signed

#371 feat: [RP Adapter] Handle request to create new PeerDID
  pkg/aries/message/msg_svc.go
  pkg/aries/message/msg_svc_test.go
  pkg/restapi/rp/operation/models.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  pkg/route/msg_svc.go
  pkg/route/service.go
  pkg/route/service_test.go
  test/bdd/features/rp_e2e.feature
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/agent/msg_svc.go
  test/bdd/pkg/rp/rp_steps.go
Labels: cla-signed

#372 chore: Updates Aries version
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/restapi/issuer/operation/support_test.go
  test/bdd/features/issuer_e2e.feature
  test/bdd/fixtures/integration/.env
  test/bdd/fixtures/integration/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/issuer/issuer_steps.go
  test/mock/cmd/issuer/main.go
Labels: cla-signed

#374 refactor: Disable rp authz did validation
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
Labels: cla-signed

#376 docs: #375 rp-adapter include `openid` in authz request
  docs/rp/integration/relying_parties.md
Labels: cla-signed, documentation

#377 chore: update aries-framework-go revision
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/crypto/crypto.go
  test/bdd/bddtests_test.go
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed
