Repository trustbloc/adapter, pull requests merged in 2021-03, with the labels that each got.

#449 feat: Use new Aries storage only, remove edge-core storage
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  cmd/adapter-rest/startcmd/start.go
  cmd/adapter-rest/startcmd/start_test.go
  go.mod
  go.sum
  pkg/aries/api.go
  pkg/crypto/util_test.go
  pkg/db/rp/rp.go
  pkg/db/rp/rp_test.go
  pkg/governance/provider.go
  pkg/governance/provider_test.go
  pkg/profile/issuer/profile.go
  pkg/profile/issuer/profile_test.go
  pkg/restapi/issuer/controller_test.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/issuer/operation/support_test.go
  pkg/restapi/rp/controller_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  pkg/restapi/rp/operation/support_test.go
  pkg/restapi/rp/operation/transient_data.go
  pkg/restapi/wallet/operation/operations.go
  pkg/restapi/wallet/operation/operations_test.go
  pkg/restapi/wallet/operation/store.go
  pkg/restapi/wallet/operation/store_test.go
  pkg/route/service.go
  pkg/route/service_test.go
  pkg/route/support_test.go
  test/bdd/bddtests_test.go
  test/bdd/fixtures/integration/.env
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#452 chore: update trustbloc-did-method
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  cmd/adapter-rest/startcmd/start.go
  go.mod
  go.sum
  pkg/did/trustbloc_did_creator.go
  pkg/did/trustbloc_did_creator_test.go
  test/bdd/fixtures/did-trustbloc/.env
  test/bdd/fixtures/integration/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/context/context.go
  test/bdd/pkg/rp/rp_steps.go
Labels: cla-signed

#451 feat: oidc integrated into request flows
  Makefile
  ci/azure-pipelines.yml
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/restapi/internal/common/oidc/oidc.go
  pkg/restapi/internal/common/oidc/oidc_test.go
  pkg/restapi/issuer/controller_test.go
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/oidc_operations.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/issuer/operation/support_test.go
  test/bdd/bddtests_test.go
  test/bdd/dockerutil/docker.go
  test/bdd/features/issuer_e2e_oidc.feature
  test/bdd/fixtures/adapter-rest/.env
  test/bdd/fixtures/adapter-rest/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/bddutil/util.go
  test/bdd/pkg/issuer/issuer_steps.go
  test/mock/cmd/issuer-login-consent/go.mod
  test/mock/cmd/issuer-login-consent/main.go
  test/mock/images/issuer-login-consent/Dockerfile
Labels: cla-signed

#455 fix: issue governance credential as final step of profile creation
  pkg/restapi/issuer/operation/operations.go
  test/bdd/fixtures/adapter-rest/docker-compose.yml
Labels: cla-signed

#456 chore: Update aries-framework-go-ext commit version
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#457 feat: avoid requesting reauthorization if access/refresh token exists.
  pkg/restapi/internal/common/oidc/oidc.go
  pkg/restapi/internal/common/oidc/oidc_test.go
  pkg/restapi/issuer/operation/oidc_operations.go
  pkg/restapi/issuer/operation/oidc_operations_test.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
Labels: cla-signed

#458 chore: release v0.1.6
  ci/version_var.sh
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  test/bdd/fixtures/did-trustbloc/.env
  test/bdd/fixtures/integration/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/mock/cmd/issuer-login-consent/go.mod
  test/mock/cmd/issuer-login-consent/go.sum
  test/mock/cmd/issuer/go.mod
  test/mock/cmd/issuer/go.sum
  test/mock/cmd/webhook/go.mod
  test/mock/cmd/webhook/go.sum
Labels: cla-signed

#459 chore: complete v0.1.6 release
  ci/version_var.sh
Labels: cla-signed

#460 feat: issuer adapter uses access tokens scoped to the credential
  cmd/issuer-adapter-vue/package-lock.json
  cmd/issuer-adapter-vue/package.json
  cmd/issuer-adapter-vue/vue.config.js
  cmd/rp-adapter-vue/package-lock.json
  cmd/rp-adapter-vue/package.json
  cmd/rp-adapter-vue/vue.config.js
  pkg/profile/issuer/profile.go
  pkg/restapi/internal/common/oidc/oidc.go
  pkg/restapi/internal/common/oidc/oidc_test.go
  pkg/restapi/issuer/operation/models.go
  pkg/restapi/issuer/operation/oidc_operations.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/wallet/operation/operations_test.go
  test/bdd/pkg/bddutil/util.go
  test/mock/cmd/issuer/main.go
Labels: cla-signed

#463 chore: update latest dependencies
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/presexch/api_test.go
  pkg/restapi/rp/operation/credentials_test.go
  test/bdd/fixtures/did-trustbloc/.env
  test/bdd/fixtures/integration/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/rp/jsonld.go
  test/mock/cmd/issuer-login-consent/go.mod
  test/mock/cmd/issuer-login-consent/go.sum
  test/mock/cmd/issuer/go.mod
  test/mock/cmd/issuer/go.sum
  test/mock/cmd/webhook/go.mod
  test/mock/cmd/webhook/go.sum
Labels: cla-signed

#465 chore: rename npm package
  ci/azure-pipelines.yml
  ci/version_var.sh
  cmd/wallet-js-client/package.json
Labels: cla-signed

#464 refactor: use AFGO impl of presentation-exchange
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  cmd/adapter-rest/startcmd/start.go
  cmd/adapter-rest/startcmd/start_test.go
  cmd/adapter-rest/startcmd/testdata/pres-def-mock.json
  docs/rp/architecture.md
  docs/rp/integration/wallets.md
  go.mod
  go.sum
  pkg/db/rp/models.go
  pkg/presentationex/provider.go
  pkg/presentationex/provider_test.go
  pkg/presexch/api.go
  pkg/presexch/api_test.go
  pkg/restapi/rp/operation/credentials.go
  pkg/restapi/rp/operation/credentials_test.go
  pkg/restapi/rp/operation/models.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  pkg/restapi/rp/operation/support_test.go
  pkg/restapi/rp/operation/testdata/context/presentation_exchange.jsonld
  pkg/vc/models.go
  test/bdd/fixtures/integration/.env
  test/bdd/fixtures/testdata/presentationdefinitions.json
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/agent/agent_controller_steps.go
  test/bdd/pkg/rp/jsonld.go
  test/bdd/pkg/rp/rp_steps.go
  test/bdd/pkg/rp/testdata/context/presentation_exchange.jsonld
Labels: blocked, cla-signed, refactor

#466 chore: rename npm package to wallet-adapter-web
  ci/azure-pipelines.yml
  ci/version_var.sh
  cmd/wallet-js-client/package.json
Labels: cla-signed

#467 chore: rename wallet-js-client to wallet-adapter-web
  ci/azure-pipelines.yml
  cmd/issuer-adapter-vue/package-lock.json
  cmd/issuer-adapter-vue/package.json
  cmd/issuer-adapter-vue/src/pages/WalletConnect.vue
  cmd/issuer-adapter-vue/vue.config.js
  cmd/rp-adapter-vue/package-lock.json
  cmd/rp-adapter-vue/package.json
  cmd/rp-adapter-vue/src/pages/Credentials.vue
  cmd/rp-adapter-vue/vue.config.js
  cmd/wallet-adapter-web/.gitignore
  cmd/wallet-adapter-web/README.md
  cmd/wallet-adapter-web/package-lock.json
  cmd/wallet-adapter-web/package.json
  cmd/wallet-adapter-web/src/index.js
  cmd/wallet-adapter-web/src/polyfill.js
  cmd/wallet-adapter-web/src/remote.js
  cmd/wallet-adapter-web/src/wallet-client.js
  cmd/wallet-adapter-web/webpack.config.js
Labels: cla-signed

#468 docs: issuer integration docs updated for OIDC flow
  docs/issuer/issuer_integration.md
  pkg/restapi/issuer/operation/operations.go
Labels: cla-signed

#469 fix: invalid pres-exch schema
  pkg/presentationex/provider.go
  pkg/presentationex/provider_test.go
  test/bdd/fixtures/testdata/presentationdefinitions.json
Labels: bug, cla-signed

#471 fix: Make TLS optional
  cmd/adapter-rest/startcmd/start.go
  cmd/adapter-rest/startcmd/start_test.go
Labels: cla-signed

#472 chore: update AFGO
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/crypto/util_test.go
  pkg/did/trustbloc_did_creator.go
  pkg/did/trustbloc_did_creator_test.go
  pkg/internal/mock/outofband/client.go
  pkg/internal/mock/outofband/service.go
  pkg/restapi/internal/mocks/protocol/outofband.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  pkg/restapi/rp/operation/support_test.go
  pkg/restapi/wallet/operation/operations.go
  pkg/restapi/wallet/operation/store.go
  pkg/route/service.go
  pkg/route/support_test.go
  test/bdd/fixtures/integration/.env
  test/bdd/fixtures/integration/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/context/context.go
  test/bdd/pkg/rp/rp_steps.go
Labels: chore, cla-signed

#473 chore: update to aries 7ec3a2c4697c512726ffaa4143e56491405dd828
  cmd/adapter-rest/go.mod
  cmd/adapter-rest/go.sum
  go.mod
  go.sum
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/rp/operation/credentials.go
  test/bdd/fixtures/did-trustbloc/.env
  test/bdd/fixtures/integration/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/agent/agent_controller_steps.go
Labels: cla-signed
